USE EJ032025
GO

SELECT * FROM DEPARTAMENTOS
SELECT * FROM EMPLEADOS

SELECT * FROM EMPLEADOS inner join DEPARTAMENTOS 
on EMPLEADOS.IDDEPARTAMENTO_EM = DEPARTAMENTOS.IDDEPARTAMENTO_DE

SELECT * FROM EMPLEADOS left join DEPARTAMENTOS 
on DEPARTAMENTOS.IDDEPARTAMENTO_DE = EMPLEADOS.IDDEPARTAMENTO_EM  

SELECT * FROM EMPLEADOS left join DEPARTAMENTOS 
on EMPLEADOS.IDDEPARTAMENTO_EM = DEPARTAMENTOS.IDDEPARTAMENTO_DE  