<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ejemplo1.aspx.cs" Inherits="ejemploGridView.ejemplo1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:GridView ID="gvLibros" runat="server" AllowPaging="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="3" OnPageIndexChanging="gvLibros_PageIndexChanging" OnRowCancelingEdit="gvLibros_RowCancelingEdit" OnRowCommand="gvLibros_RowCommand" OnRowDeleting="gvLibros_RowDeleting" OnRowEditing="gvLibros_RowEditing" OnRowUpdating="gvLibros_RowUpdating" OnSelectedIndexChanging="gvLibros_SelectedIndexChanging" PageSize="2">
                <Columns>
                    <asp:TemplateField HeaderText="Id Libro">
                        <EditItemTemplate>
                            <asp:Label ID="lbl_eit_idLibro" runat="server" Text='<%# Bind("IdLibro") %>'></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lbl_it_idLibro" runat="server" Text='<%# Bind("IdLibro") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Titulo">
                        <EditItemTemplate>
                            <asp:TextBox ID="txt_eit_Titulo" runat="server" Text='<%# Bind("Titulo") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lbl_it_Titulo" runat="server" Text='<%# Bind("Titulo") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Precio">
                        <EditItemTemplate>
                            <asp:TextBox ID="txt_eit_Precio" runat="server" Text='<%# Bind("Precio") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lbl_it_Precio" runat="server" Text='<%# Bind("Precio") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Autor del Libro">
                        <EditItemTemplate>
                            <asp:TextBox ID="txt_eit_Autor" runat="server" Text='<%# Bind("Autor") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lbl_it_Autor" runat="server" Text='<%# Bind("Autor") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:ButtonField ButtonType="Button" CommandName="eventoComprar" Text="Comprar" />
                </Columns>
                <FooterStyle BackColor="White" ForeColor="#000066" />
                <HeaderStyle BackColor="#006699" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="White" ForeColor="#000066" HorizontalAlign="Left" />
                <RowStyle ForeColor="#000066" />
                <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#F1F1F1" />
                <SortedAscendingHeaderStyle BackColor="#007DBB" />
                <SortedDescendingCellStyle BackColor="#CAC9C9" />
                <SortedDescendingHeaderStyle BackColor="#00547E" />
            </asp:GridView>
            <br />
            <br />
            <asp:Label ID="lblMensaje" runat="server"></asp:Label>
        </div>
    </form>
</body>
</html>
